events {
    worker_connections 1024;
}

http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    # Configurazione HTTP unica per Outgrow
    server {
        listen 80;
        server_name localhost;

        # Gestione dei file statici (immagini/video dei post) serviti direttamente da Nginx
        location /uploads/ {
            root /usr/share/nginx/html;
            try_files $uri =404;
        }

        # Gestione delle richieste API verso il Backend Express
        location / {
            proxy_pass http://backend:3000; # "backend" è il nome del servizio nel docker-compose
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection 'upgrade';
            proxy_set_header Host $host;
            proxy_cache_bypass $http_upgrade;
            
            # Manteniamo il limite di upload per le foto/video delle sfide
            client_max_body_size 105M;
        }
    }
}